api_version = "2026-01"

[[extensions]]
name = "t:name"
handle = "split-rates"
type = "function"
uid = "3eba2786-ff85-eb51-9845-51a882a717a100bf0f7e"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.fulfillment-constraints.generate.run"
  input_query = "src/cart_fulfillment_constraints_generate_run.graphql"
  export = "cart-fulfillment-constraints-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
